# Site settings
title: Travis CI Build Site
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://next.travis-ci.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
